/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Dirty {
  get(key: string): string | null
  set(key: string, val: string): void
  remove(key: string): void
  findKeys(key: string, notKey?: string | undefined | null): Array<string>
  close(): void
}

export declare class KeyValueDB {
  constructor(filename: string)
  get(key: string): string | null
  set(key: string, value: string): void
  remove(key: string): void
  findKeys(key: string, notKey?: string | undefined | null): Array<string>
  close(): void
  destroy(): void
}

export declare class MemoryDB {
  constructor()
  get(key: string): string | null
  set(key: string, value: string): void
  remove(key: string): void
  findKeys(key: string, notKey?: string | undefined | null): Array<string>
  close(): void
}

export declare class SQLite {
  constructor(filename: string)
  findKeys(key: string, notKey?: string | undefined | null): Array<string>
  get(key: string): string | null
  set(key: string, value: string): number | null
  remove(key: string): void
  doBulk(bulkObject: Array<BulkObject>): void
  close(): void
}

export interface BulkObject {
  type: string
  key: string
  value?: string
}

