/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Database {
  constructor(type: string, settings: Settings, wrapperSettings?: WrapperSettings | undefined | null)
  init(): Promise<void>
  close(): Promise<void>
  flush(): Promise<void>
  get(key: string): Promise<any | null>
  set(key: string, value: any): Promise<void>
  remove(key: string): Promise<void>
  getSub(key: string, path: Array<string>): Promise<any | null>
  setSub(key: string, path: Array<string>, value?: any | undefined | null): Promise<void>
  findKeys(key: string, notKey?: string | undefined | null): Promise<Array<string>>
  metrics(): Metrics
}

export interface Metrics {
  reads: number
  writes: number
  removes: number
  cacheHits: number
  cacheMisses: number
  flushes: number
  bulks: number
}

export interface Settings {
  filename?: string
  host?: string
  port?: number
  user?: string
  password?: string
  database?: string
  url?: string
  charset?: string
  engine?: string
  table?: string
  collection?: string
  dbName?: string
  connectionString?: string
  api?: string
  baseIndex?: string
  server?: string
  columnFamily?: string
  requestTimeout?: number
  queryTimeout?: number
  bulkLimit?: number
  idleTimeoutMillis?: number
  min?: number
  max?: number
  migrateToNewerSchema?: boolean
  parseJson?: boolean
  pool?: boolean
  clientOptions?: any
}

export interface WrapperSettings {
  /** LRU read-cache capacity. Default 1000. 0 disables. */
  cache?: number
  /** Write buffer flush interval in ms. Default 100. 0 disables buffering. */
  writeInterval?: number
  /** Maximum ops per bulk flush. Default 100. */
  bulkLimit?: number
  /** Encode values as JSON strings before passing to the backend. Defaults per-backend. */
  json?: boolean
}
