/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Couch {
  constructor(settings: CouchDbSettings)
  init(): Promise<void>
  get(key: string): Promise<string | null>
  findKeys(key: string, notKey?: string | undefined | null): Promise<Array<string>>
  set(key: string, value: string): Promise<void>
  doBulk(bulk: Array<BulkObject>): Promise<void>
  remove(key: string): Promise<void>
  close(): void
  destroy(): Promise<void>
}

export declare class Dirty {
  constructor(filename: string)
  get(key: string): string | null
  set(key: string, val: string): void
  remove(key: string): void
  findKeys(key: string, notKey?: string | undefined | null): Array<string>
  close(): void
}

export declare class KeyValueDB {
  constructor(filename: string)
  get(key: string): string | null
  set(key: string, value: string): void
  remove(key: string): void
  findKeys(key: string, notKey?: string | undefined | null): Array<string>
  close(): void
  destroy(): void
}

export declare class MemoryDB {
  constructor()
  get(key: string): string | null
  set(key: string, value: string): void
  remove(key: string): void
  findKeys(key: string, notKey?: string | undefined | null): Array<string>
  close(): void
}

export declare class Postgres {
  constructor(filename: PostgresSettings)
  findKeys(key: string, notKey?: string | undefined | null): Array<string>
  get(key: string): string | null
  set(key: string, value: string): number | null
  remove(key: string): void
  doBulk(bulkObject: Array<BulkObject>): void
  close(): void
  destroy(): void
}

export declare class SQLite {
  constructor(filename: string)
  findKeys(key: string, notKey?: string | undefined | null): Array<string>
  get(key: string): string | null
  set(key: string, value: string): number | null
  remove(key: string): void
  doBulk(bulkObject: Array<BulkObject>): void
  close(): void
}

export interface BulkObject {
  type: string
  key: string
  value?: string
}

export interface CouchDbSettings {
  user: string
  password: string
  host: string
  port: number
  database: string
}

export interface PostgresSettings {
  user: string
  database: string
  port: number
  host: string
  password: string
}
